blank_issues_enabled: false
contact_links:
  - name: 📖 Repository documentation
    url: https://github.com/deidron/bpmsoft-net-core-cookbook-single-test/blob/main/README.md
    about: Repository structure, building and packing packages
